# Generated by Django 3.2.7 on 2021-12-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20211213_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='crs',
            new_name='crss',
        ),
    ]
