# Generated by Django 3.2.7 on 2021-12-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_rename_crs_stock_crss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='crss',
            new_name='crs',
        ),
    ]
