# Generated by Django 3.2.7 on 2021-12-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_rename_crs_stock_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='id_d',
            field=models.CharField(default=1, max_length=40, verbose_name='id'),
            preserve_default=False,
        ),
    ]
