# Generated by Django 3.2.7 on 2021-12-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stock_id_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id_d',
            field=models.CharField(max_length=40, verbose_name='idd'),
        ),
    ]
